### ISSUE TITLE
Can't upload files to s3 using docker image

### ISSUE THREAD

**Issue by lluishi93** [directus/docker#111]
I'm having trouble while uploading filles from docker container to s3. I have set the following variables with their values, I have my S3 bucket with public permissions and I am using a root access/secret key pair in AWS, and I’m not succeeding at uploading files to the bucket, and when checking the trace from the server I cannot get any information besides http response with a 500 http code,  am I missing something? The upload gets stuck for a while at 95 and then I get the error

DIRECTUS_STORAGE_ADAPTER
DIRECTUS_STORAGE_ROOT
DIRECTUS_STORAGE_ROOTURL
DIRECTUS_STORAGE_THUMBROOT
DIRECTUS_STORAGE_KEY
DIRECTUS_STORAGE_SECRET
DIRECTUS_STORAGE_REGION
DIRECTUS_STORAGE_BUCKET

![image](https://user-images.githubusercontent.com/14786440/77696299-715a7380-6fad-11ea-90cd-77a5d144e1e0.png)

**Comment by lluishi93** [comment]
@WoLfulus Could you please provide me some s3 configuration setup? The one seen in the examples doesn't seem to work for me, so maybe I'm missing something

**Comment by notio-ca** [comment]
I was able to reproduce, with the environment variable, and then I decided to DIRECTUS_USE_ENV: 0 and use the /config/api.php as configuration. I am using the same setting on a Djando python app and works properly. I took exactly the same config ([here](https://docs.directus.io/extensions/storage-adapters.html#using-aws-s3)) and end up with:

'storage' => [
    'adapter' => 's3',
    'key' => 'AKIAIBETVA6C7xxxxxxx',
    'secret' => 'a/pKdtYjOT23qxxxxxxxxxxxxxxxHFlzuOKCDxMG',
    'bucket' => 'cdn.xxxx.com',
    'version' => 'latest',
    'region' => 'us-east-1',
    'options' => [
        'ACL' => 'public-read',
        'CacheControl' => 'max-age=604800'
    ],
    'endpoint' => 's3-endpoint',
    'root' => '/',
    'thumb_root' => '/thumbnails',
    'root_url' => 'http://cdn.xxxx.com.s3-website-us-east-1.amazonaws.com',
]

Thanks for this great headless CMS, the best from my point of view, but without clouding storage, we can't go forward.

**Comment by notio-ca** [comment]
@lluishi93 this is working properly, here is my working docker-compose.yml:

version: "2.2"
services:
  directus:
    image: directus/directus:v8-apache
    container_name: directus
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_AUTH_PUBLICKEY: "xxxxxxxxxxxxxxxxxx"
      DIRECTUS_AUTH_SECRETKEY: "xxxxxxxxxxxxxxxxxx"
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "xxx"
      DIRECTUS_DATABASE_PASSWORD: "xxx"
      DIRECTUS_STORAGE_ADAPTER: "s3"
      DIRECTUS_STORAGE_ROOT: "/"
      DIRECTUS_STORAGE_ROOTURL: "http://cdn.xxxx.com.s3-website-us-east-1.amazonaws.com"
      DIRECTUS_STORAGE_THUMBROOT: "/thumbnails"
      DIRECTUS_STORAGE_VERSION: "latest"
      DIRECTUS_STORAGE_KEY: "AKIAIBETVAxxxxxxxxxx"
      DIRECTUS_STORAGE_SECRET: "a/pKdtxxxxxxxxxxiNonqirSsOK1HFxxxxxxxxxx"
      DIRECTUS_STORAGE_REGION: "us-east-1"
      DIRECTUS_STORAGE_BUCKET: "cdn.xxxx.com"
      DIRECTUS_STORAGE_ENDPOINT: "https://s3.amazonaws.com" # ! IMPORTANT FIT ALL
      DIRECTUS_MAIL_DEFAULT_TRANSPORT: "smtp"
      DIRECTUS_MAIL_DEFAULT_FROM: "xxx@xxx.com"
      DIRECTUS_MAIL_DEFAULT_HOST: "smtp"
      DIRECTUS_MAIL_DEFAULT_PORT: "25"

**Comment by oliversavio** [comment]
I too have this issue. I notice the call to `ListObjects` when uploading a file fails, I've given the IAM use full access to S3 and I'm able to list / write objects via CLI.

```
directus_1  | Stack trace:
directus_1  | #0 /var/directus/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError
directus_1  | #1 /var/directus/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\WrappedHttpHandler->Aws\{closure}
directus_1  | #2 /var/directus/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler
directus_1  | #3 /var/directus/vendor/guzzlehttp/promises/src/RejectedPromise.php(40): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}
directus_1  | #4 /var/directus/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}
directus_1  | #5 /var/directus/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run
directus_1  | #6 /var/directus/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick
directus_1  | #7 /var/directus/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute
directus_1  | #8 /var/directus/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn
directus_1  | #9 /var/directus/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending
directus_1  | #10 /var/directus/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList
directus_1  | #11 /var/directus/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending
directus_1  | #12 /var/directus/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList
directus_1  | #13 /var/directus/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending
directus_1  | #14 /var/directus/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait
directus_1  | #15 /var/directus/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(715): Aws\AwsClient->execute
directus_1  | #16 /var/directus/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(238): League\Flysystem\AwsS3v3\AwsS3Adapter->doesDirectoryExist
directus_1  | #17 /var/directus/vendor/league/flysystem/src/Filesystem.php(57): League\Flysystem\AwsS3v3\AwsS3Adapter->has
directus_1  | #18 /var/directus/src/core/Directus/Filesystem/Filesystem.php(29): League\Flysystem\Filesystem->has
directus_1  | #19 /var/directus/src/core/Directus/Filesystem/Files.php(665): Directus\Filesystem\Filesystem->exists
directus_1  | #20 /var/directus/src/core/Directus/Filesystem/Files.php(715): Directus\Filesystem\Files->uniqueName
directus_1  | #21 /var/directus/src/core/Directus/Filesystem/Files.php(307): Directus\Filesystem\Files->getFileName
directus_1  | #22 /var/directus/src/core/Directus/Services/FilesServices.php(94): Directus\Filesystem\Files->saveData
directus_1  | #23 /var/directus/src/core/Directus/Services/FilesServices.php(60): Directus\Services\FilesServices->getSaveData
```

**Comment by jcharnley** [comment]
am having some the same issue. might have something to do with the bucket policy...

**Comment by jcharnley** [comment]
Below works for me I got rid of the ENDPOINT, the ROOTURL was confusing as I had to upload a file to see the url. Also good to define folders where you want the images to go. If futher issues it could be linked to your bucket policy

  DIRECTUS_STORAGE_ROOT: "/uploads"
      DIRECTUS_STORAGE_THUMBROOT: "/thumbnails"
      DIRECTUS_STORAGE_ADAPTER: "s3"
      DIRECTUS_STORAGE_VERSION: "latest"
      DIRECTUS_STORAGE_ROOTURL: "https://s3-eu-west-1.amazonaws.com/project-name"
      DIRECTUS_STORAGE_KEY: "key"
      DIRECTUS_STORAGE_SECRET: "sercret/gxI"
      DIRECTUS_STORAGE_REGION: "eu-west-1"
      DIRECTUS_STORAGE_BUCKET: "project-name"

**Comment by oliversavio** [comment]
Super! I disabled ENDPOINT and set my S3 bucket to public access and it works now.
