### ISSUE TITLE
Email does not work out of the box

### ISSUE THREAD

**Issue by samvasko** [directus/docker#26]
Emails are not working out of the box due to lack of SMTP when using `'transport' => 'sendmail',`
POSTing the `users/invite` endpoint results in following error:

```json
{
    "error": {
        "code": null,
        "message": "Expected response code 220 but got code \"\", with message \"\""
    }
}
```

<details><summary>With following traceback: (click to expand) </summary>
<p>

```
[2019-02-13 10:07:20] api[_].ERROR: Swift_TransportException: Expected response code 220 but got code "", with message "" in /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(289): Swift_Transport_AbstractSmtpTransport->_assertResponseCode
#1 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(117): Swift_Transport_AbstractSmtpTransport->_readGreeting
#2 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(51): Swift_Transport_AbstractSmtpTransport->start
#3 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_SendmailTransport->start
#4 /var/www/html/src/core/Directus/Mail/Mailer.php(76): Swift_Mailer->send
#5 /var/www/html/src/core/Directus/Mail/Mailer.php(42): Directus\Mail\Mailer->sendWithContent
#6 /var/www/html/src/helpers/mail.php(25): Directus\Mail\Mailer->sendWithTemplate
#7 /var/www/html/src/helpers/mail.php(214): Directus\send_mail_with_template
#8 /var/www/html/src/core/Directus/Services/UsersService.php(232): Directus\send_user_invitation_email
#9 /var/www/html/src/core/Directus/Services/UsersService.php(175): Directus\Services\UsersService->sendInvitationTo
#10 /var/www/html/src/endpoints/Users.php(104): Directus\Services\UsersService->invite
#11 [internal function]: Directus\Api\Routes\Users->invite
#12 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#13 /var/www/html/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#14 /var/www/html/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#15 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#16 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#17 [internal function]: Slim\DeferredCallable->__invoke
#18 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#19 /var/www/html/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(81): Slim\Route->Slim\{closure}
#20 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#21 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#22 [internal function]: Slim\DeferredCallable->__invoke
#23 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#24 /var/www/html/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#25 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#26 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#27 [internal function]: Slim\DeferredCallable->__invoke
#28 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#29 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#30 /var/www/html/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#31 /var/www/html/vendor/slim/slim/Slim/App.php(516): Slim\Route->run
#32 /var/www/html/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#33 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#34 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#35 [internal function]: Slim\DeferredCallable->__invoke
#36 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#37 /var/www/html/vendor/wellingguzman/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#38 /var/www/html/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#39 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#40 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#41 [internal function]: Slim\DeferredCallable->__invoke
#42 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#43 /var/www/html/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#44 [internal function]: RKA\Middleware\IpAddress->__invoke
#45 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#46 [internal function]: Slim\DeferredCallable->__invoke
#47 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#48 /var/www/html/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#49 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#50 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#51 [internal function]: Slim\DeferredCallable->__invoke
#52 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#53 /var/www/html/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#54 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#55 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#56 [internal function]: Slim\DeferredCallable->__invoke
#57 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#58 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#59 /var/www/html/vendor/slim/slim/Slim/App.php(407): Slim\App->callMiddlewareStack
#60 /var/www/html/vendor/slim/slim/Slim/App.php(315): Slim\App->process
#61 /var/www/html/src/core/Directus/Application/Application.php(161): Slim\App->run
#62 /var/www/html/public/index.php(5): Directus\Application\Application->run [] []
```

<p/>
</details>

**Comment by Nitwel** [comment]
Having the same issue in the non docker version so maybe move the issue to directus/api?

**Comment by samvasko** [comment]
I posted this here because the issues cannot likely be resolved for all possible combinations of servers and OS but the docker should work out of the box.

**Comment by WoLfulus** [comment]
@samvasko did you solve this on your end? We'll not be bundling sendmail by default on our docker images, but you can easily extend our images and add sendmail to a custom image if it's a requirement.
