### ISSUE TITLE
'Duplicate entry 'project_name' for key 'idx_key' when creating new project

### ISSUE THREAD

**Issue by radoslawadamiakinfinitec** [directus/docker#90]
# Bug Report

## Steps to Reproduce

1. Follow steps of Docker installation
https://docs.directus.io/installation/docker.html
2. Try to create new project using endpoint:
http://localhost:8080/admin/#/install
2.a Create new database inside mysql running container:
`docker exec -it directus_mysql_1 mysql -uroot -p`
`MySql> CREATE DATABASE test;`
`MySql> GRANT ALL PRIVILEGES ON test.* TO 'directus'@'%';`

3. Checking steps gives warning 

4. Click Install 1st time in last step - it gives an exception `Duplicate entry 'project_name' for key 'idx_key'`

5. Click Install 2nd time - it gives an error: `A project named "test" already exists.`

## Expected Behavior

It is possible to create new project.

## Actual Behavior

After 1st click on Install: `Duplicate entry 'project_name' for key 'idx_key'`
After 2nd click on Install: `A project named "test" already exists.`

`docker logs directus_directus_1`

After 1st click on Install:
```
directus_1  | [2020-01-23 09:40:27] api[].ERROR: Zend\Db\Adapter\Exception\InvalidQueryException: Statement could not be executed (23000 - 1062 - Duplicate entry 'project_name' for key 'idx_key') in /var/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244
directus_1  | Stack trace:
directus_1  | #0 /var/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(308): Zend\Db\Adapter\Driver\Pdo\Statement->execute
directus_1  | directus/directus#1 /var/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Zend\Db\TableGateway\AbstractTableGateway->executeInsert
directus_1  | directus/directus#2 /var/directus/src/core/Directus/Util/Installation/InstallerUtils.php(333): Zend\Db\TableGateway\AbstractTableGateway->insert
directus_1  | directus/directus#3 /var/directus/src/core/Directus/Services/ProjectService.php(113): Directus\Util\Installation\InstallerUtils::addDefaultSettings
directus_1  | directus/directus#4 /var/directus/src/endpoints/ProjectsCreate.php(17): Directus\Services\ProjectService->create
directus_1  | directus/directus#5 [internal function]: Directus\Api\Routes\ProjectsCreate->__invoke
directus_1  | directus/directus#6 /var/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
directus_1  | directus/directus#7 /var/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
directus_1  | directus/directus#8 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke
directus_1  | directus/directus#9 /var/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
directus_1  | directus/directus#10 /var/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
directus_1  | directus/directus#11 /var/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
directus_1  | directus/directus#12 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
directus_1  | directus/directus#13 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus_1  | directus/directus#14 [internal function]: Slim\DeferredCallable->__invoke
directus_1  | directus/directus#15 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus_1  | directus/directus#16 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
directus_1  | directus/directus#17 /var/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
directus_1  | directus/directus#18 /var/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
directus_1  | directus/directus#19 /var/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
directus_1  | directus/directus#20 /var/directus/public/index.php(5): Directus\Application\Application->run [] []
```

After 2nd click on Install:

```
directus_1  | [2020-01-23 10:52:41] api[].ERROR: Directus\Exception\ProjectAlreadyExistException: A project named "test" already exists. in /var/directus/src/core/Directus/Services/ProjectService.php:96
directus_1  | Stack trace:
directus_1  | #0 /var/directus/src/endpoints/ProjectsCreate.php(17): Directus\Services\ProjectService->create
directus_1  | directus/directus#1 [internal function]: Directus\Api\Routes\ProjectsCreate->__invoke
directus_1  | directus/directus#2 /var/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
directus_1  | directus/directus#3 /var/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
directus_1  | directus/directus#4 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke
directus_1  | directus/directus#5 /var/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
directus_1  | directus/directus#6 /var/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
directus_1  | directus/directus#7 /var/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
directus_1  | directus/directus#8 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
directus_1  | directus/directus#9 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus_1  | directus/directus#10 [internal function]: Slim\DeferredCallable->__invoke
directus_1  | directus/directus#11 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus_1  | directus/directus#12 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
directus_1  | directus/directus#13 /var/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
directus_1  | directus/directus#14 /var/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
directus_1  | directus/directus#15 /var/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
directus_1  | directus/directus#16 /var/directus/public/index.php(5): Directus\Application\Application->run [] []
```

## Other Context & Screenshots
![directus-missing-mysqli](https://user-images.githubusercontent.com/54141066/72945107-276dcb00-3d7b-11ea-8c4a-29d60d68a33b.png)

When I call an endpoint `/server/projects` it returns still:

`{"data":["_"],"public":true}`

I have checked with different project names, every time I get either directus doesn't have rights to access db (when DB doesn't exist) or duplicate entry (above).

## Technical Details

- Device: Desktop
- OS: Ubuntu 18.04.3 LTS
- Web Server: As in docker image
- PHP Version: As in docker image
- Database: As in docker image
- Directus Release Version:v 8-apache
  - App Version: IDK
  - API Version: IDK
- Install Method: docker latest image

**Comment by WoLfulus** [comment]
Have you disabled environment variable loading in that case? Docker only supports a single project if you're loading from environment variables.

https://docs.directus.io/docker/overview.html#configuring

As for mysqli dependecy, we just released a hotfix that should fix it.

https://github.com/directus/docker/releases/tag/v8.4.0%2Bdocker.1

You can pull the image again to check if the warning is gone.

**Comment by WoLfulus** [comment]
Have you solved this @radoslawadamiakinfinitec ? Just let me know so I can close this one.

**Comment by radoslawadamiakinfinitec** [comment]
@WoLfulus Yes I've solved it by switching from ENV vars to use config files.

**Comment by WoLfulus** [comment]
Cool! :)
